# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/Workspace/Vivado_16.4/2017_12_7_FSM/FSM.cache/wt [current_project]
set_property parent.project_path E:/Workspace/Vivado_16.4/2017_12_7_FSM/FSM.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/Workspace/Vivado_16.4/2017_12_7_FSM/FSM.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib E:/Workspace/Vivado_16.4/2017_12_7_FSM/Design/Code/FSM_book.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top FSM_book -part xc7a35tcpg236-1


write_checkpoint -force -noxdef FSM_book.dcp

catch { report_utilization -file FSM_book_utilization_synth.rpt -pb FSM_book_utilization_synth.pb }
